const departures = [
  {time:"06:20",destination:"Kraljevo",via:"Trstenik",platform:1,carrier:"Demo Trans",price:450,status:"onTime"},
  {time:"07:05",destination:"Kruševac",via:"Trstenik",platform:2,carrier:"Morava Demo",price:620,status:"onTime"},
  {time:"08:15",destination:"Beograd",via:"Kraljevo · Kragujevac",platform:3,carrier:"Demo Trans",price:1450,status:"onTime"},
  {time:"09:40",destination:"Niš",via:"Kruševac",platform:2,carrier:"Jug Demo",price:1250,status:"delayed"},
  {time:"11:30",destination:"Novi Pazar",via:"Kraljevo · Raška",platform:4,carrier:"Ibar Demo",price:980,status:"onTime"},
  {time:"13:10",destination:"Kragujevac",via:"Kraljevo",platform:1,carrier:"Demo Trans",price:780,status:"onTime"},
  {time:"15:45",destination:"Beograd",via:"Kragujevac",platform:3,carrier:"Morava Demo",price:1450,status:"onTime"},
  {time:"18:20",destination:"Kraljevo",via:"direktno",platform:2,carrier:"Ibar Demo",price:450,status:"onTime"},
  {time:"20:10",destination:"Kruševac",via:"Trstenik",platform:1,carrier:"Jug Demo",price:620,status:"delayed"}
];
const translations={
  sr:{demo:"Portfolio projekat — prikazani polasci i cene su demonstracioni podaci.",station:"Autobuska stanica",departures:"Polasci",stationInfo:"Stanica",contact:"Kontakt",eyebrow:"Put počinje ovde",heroTitle:"Iz banje,<br><em>pravo na put.</em>",heroSubtitle:"Pronađite polazak, proverite peron i isplanirajte sledeće putovanje — brzo i jednostavno.",findDeparture:"Pronađi polazak",stationDetails:"Informacije o stanici",nextDeparture:"Sledeći polazak",onTime:"Na vreme",delayed:"Kašnjenje 15 min",platform:"Peron",carrier:"Prevoznik",duration:"Trajanje",timetable:"Red vožnje",todayDepartures:"Današnji polasci",destination:"Destinacija",period:"Period",allDay:"Ceo dan",morning:"Pre podne",afternoon:"Posle podne",evening:"Veče",search:"Pretraži",time:"Vreme",route:"Relacija",price:"Cena",status:"Status",noResults:"Nema pronađenih polazaka.",tryAnother:"Pokušajte drugu destinaciju ili period.",youAreHere:"Ovde ste",centerDistance:"Centar Vrnjačke Banje · 1,2 km",beforeTravel:"Pre putovanja",everythingNearby:"Sve što vam treba,<br>na jednom mestu.",stationText:"Stanica je lako dostupna iz centra. Dođite najmanje 15 minuta pre polaska i proverite broj perona na displeju.",waitingRoom:"Čekaonica",cafe:"Kafe i užina",freeNetwork:"Besplatna mreža",infoDesk:"Info pult",travelNotice:"Obaveštenje",arriveEarly:"Planirajte dolazak ranije.",noticeText:"Tokom vikenda i praznika moguća su odstupanja od reda vožnje. Informacije u ovom portfolio projektu nisu zvanične.",demoProject:"Nezvanični portfolio projekat",navigation:"Navigacija",important:"Važno",footerWarning:"Ne koristiti za stvarno planiranje putovanja. Svi podaci su demonstracioni.",placeholder:"Pretraži grad...",direct:"direktno"},
  en:{demo:"Portfolio project — departures and prices shown are demonstration data.",station:"Bus station",departures:"Departures",stationInfo:"Station",contact:"Contact",eyebrow:"Your journey starts here",heroTitle:"From the spa,<br><em>straight to the road.</em>",heroSubtitle:"Find a departure, check your platform and plan your next journey — quickly and easily.",findDeparture:"Find a departure",stationDetails:"Station information",nextDeparture:"Next departure",onTime:"On time",delayed:"15 min delay",platform:"Platform",carrier:"Operator",duration:"Duration",timetable:"Timetable",todayDepartures:"Today's departures",destination:"Destination",period:"Period",allDay:"All day",morning:"Morning",afternoon:"Afternoon",evening:"Evening",search:"Search",time:"Time",route:"Route",price:"Price",status:"Status",noResults:"No departures found.",tryAnother:"Try another destination or time period.",youAreHere:"You are here",centerDistance:"Vrnjačka Banja centre · 1.2 km",beforeTravel:"Before you travel",everythingNearby:"Everything you need,<br>in one place.",stationText:"The station is easily accessible from the town centre. Arrive at least 15 minutes early and check the platform display.",waitingRoom:"Waiting room",cafe:"Café and snacks",freeNetwork:"Free network",infoDesk:"Information desk",travelNotice:"Travel notice",arriveEarly:"Plan to arrive early.",noticeText:"Weekend and holiday schedules may vary. Information in this portfolio project is not official.",demoProject:"Unofficial portfolio project",navigation:"Navigation",important:"Important",footerWarning:"Do not use for actual journey planning. All information is demonstrational.",placeholder:"Search city...",direct:"direct"}
};
let language="sr";
const body=document.getElementById("departuresBody"),empty=document.getElementById("emptyState"),search=document.getElementById("searchInput"),period=document.getElementById("periodFilter");
function periodOf(time){const hour=Number(time.split(":")[0]);return hour<12?"morning":hour<18?"afternoon":"evening"}
function render(){const query=search.value.trim().toLocaleLowerCase("sr");const filtered=departures.filter(d=>(!query||d.destination.toLocaleLowerCase("sr").includes(query))&&(period.value==="all"||periodOf(d.time)===period.value));body.innerHTML=filtered.map(d=>`<tr><td>${d.time}</td><td class="destination"><strong>${d.destination}</strong><small>${language==="en"&&d.via==="direktno"?"direct":d.via}</small></td><td>${d.platform}</td><td>${d.carrier}</td><td>${d.price.toLocaleString(language==="sr"?"sr-RS":"en-US")} RSD</td><td><span class="status ${d.status==="delayed"?"delayed":""}">${translations[language][d.status]}</span></td></tr>`).join("");empty.hidden=filtered.length>0}
function setLanguage(lang){language=lang;document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const value=translations[lang][el.dataset.i18n];if(value)el.innerHTML=value});search.placeholder=translations[lang].placeholder;document.getElementById("languageButton").textContent=lang==="sr"?"EN":"SR";document.getElementById("currentDate").textContent=new Intl.DateTimeFormat(lang==="sr"?"sr-Latn-RS":"en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());render()}
search.addEventListener("input",render);period.addEventListener("change",render);document.getElementById("searchButton").addEventListener("click",render);document.getElementById("languageButton").addEventListener("click",()=>setLanguage(language==="sr"?"en":"sr"));setLanguage("sr");
