const defaultProducts=[
 {id:1,name:"Espresso",description:"Single origin blend",category:"coffee",price:190,icon:"☕",available:true},
 {id:2,name:"Cappuccino",description:"Espresso · milk foam",category:"coffee",price:260,icon:"☕",available:true},
 {id:3,name:"Flat White",description:"Double shot · steamed milk",category:"coffee",price:290,icon:"☕",available:true},
 {id:4,name:"Iced Latte",description:"Espresso · milk · ice",category:"cold",price:320,icon:"🥤",available:true},
 {id:5,name:"Fresh Lemonade",description:"Lemon · mint · soda",category:"cold",price:290,icon:"🍋",available:true},
 {id:6,name:"Cold Brew",description:"18-hour slow brew",category:"cold",price:330,icon:"🧊",available:false},
 {id:7,name:"Croissant",description:"Butter · flaky pastry",category:"food",price:220,icon:"🥐",available:true},
 {id:8,name:"Club Sandwich",description:"Chicken · salad · toast",category:"food",price:590,icon:"🥪",available:true},
 {id:9,name:"Avocado Toast",description:"Sourdough · avocado",category:"food",price:520,icon:"🥑",available:true},
 {id:10,name:"Cheesecake",description:"Cream cheese · berries",category:"dessert",price:390,icon:"🍰",available:true},
 {id:11,name:"Chocolate Cake",description:"Dark chocolate · cream",category:"dessert",price:410,icon:"🍫",available:true},
 {id:12,name:"Cinnamon Roll",description:"Cinnamon · vanilla glaze",category:"dessert",price:280,icon:"🍥",available:true}
];
const tr={
 en:{register:"Register",kitchen:"Kitchen",menu:"Menu",reports:"Reports",shiftManager:"Shift manager",demoNotice:"Portfolio demo · No real payments or fiscal receipts",resetDemo:"Reset demo",newOrder:"New order",open:"Open",currentOrder:"Current order",dineIn:"Dine in",takeaway:"Takeaway",table:"Table",emptyOrder:"Order is empty",addFromMenu:"Choose an item from the menu",subtotal:"Subtotal",service:"Service",total:"Total",sendKitchen:"Send to kitchen",all:"All",coffee:"Coffee",cold:"Cold drinks",food:"Food",dessert:"Desserts",soldOut:"Sold out",searchMenu:"Search menu...",orderSent:"Order sent to kitchen",orderEmpty:"Add an item first",liveOrders:"Live orders",kitchenBoard:"Kitchen board",live:"Live",waiting:"Waiting",preparing:"Preparing",ready:"Ready",clearReady:"Clear ready orders",startPreparing:"Start preparing",markReady:"Mark as ready",noOrders:"No orders here",catalog:"Catalog",menuManagement:"Menu management",addItem:"+ Add item",totalItems:"Total items",available:"Available",unavailable:"Unavailable",item:"Item",category:"Category",price:"Price",availability:"Availability",addMenuItem:"Add menu item",itemName:"Item name",priceRsd:"Price (RSD)",shortDescription:"Short description",cancel:"Cancel",saveItem:"Save item",itemAdded:"Menu item added",overview:"Overview",dailyReport:"Daily report",exportCsv:"Export CSV",revenue:"Revenue",orders:"Orders",averageOrder:"Average order",topItem:"Top item",demoSales:"From demo orders today",sentKitchen:"Sent to kitchen",byQuantity:"By quantity sold",sales:"Sales",ordersByHour:"Orders by hour",performance:"Performance",popularItems:"Popular items",activity:"Activity",recentOrders:"Recent orders",noSales:"No sales yet",qty:"sold",resetConfirm:"Reset all demo data?",demoReset:"Demo data reset",exported:"Report exported"},
 sr:{register:"Kasa",kitchen:"Kuhinja",menu:"Meni",reports:"Izveštaji",shiftManager:"Vođa smene",demoNotice:"Portfolio demo · Bez pravih plaćanja i fiskalnih računa",resetDemo:"Resetuj demo",newOrder:"Nova porudžbina",open:"Otvoreno",currentOrder:"Trenutna porudžbina",dineIn:"U lokalu",takeaway:"Za poneti",table:"Sto",emptyOrder:"Porudžbina je prazna",addFromMenu:"Izaberite proizvod iz menija",subtotal:"Međuzbir",service:"Usluga",total:"Ukupno",sendKitchen:"Pošalji u kuhinju",all:"Sve",coffee:"Kafa",cold:"Hladna pića",food:"Hrana",dessert:"Dezerti",soldOut:"Rasprodato",searchMenu:"Pretraži meni...",orderSent:"Porudžbina poslata u kuhinju",orderEmpty:"Prvo dodajte proizvod",liveOrders:"Aktivne porudžbine",kitchenBoard:"Kuhinjska tabla",live:"Uživo",waiting:"Čeka",preparing:"Priprema",ready:"Spremno",clearReady:"Ukloni spremne",startPreparing:"Počni pripremu",markReady:"Označi spremno",noOrders:"Nema porudžbina",catalog:"Katalog",menuManagement:"Upravljanje menijem",addItem:"+ Dodaj proizvod",totalItems:"Ukupno proizvoda",available:"Dostupno",unavailable:"Nedostupno",item:"Proizvod",category:"Kategorija",price:"Cena",availability:"Dostupnost",addMenuItem:"Dodaj proizvod",itemName:"Naziv proizvoda",priceRsd:"Cena (RSD)",shortDescription:"Kratak opis",cancel:"Otkaži",saveItem:"Sačuvaj",itemAdded:"Proizvod dodat",overview:"Pregled",dailyReport:"Dnevni izveštaj",exportCsv:"Izvezi CSV",revenue:"Prihod",orders:"Porudžbine",averageOrder:"Prosečna porudžbina",topItem:"Najprodavanije",demoSales:"Iz demo porudžbina danas",sentKitchen:"Poslato u kuhinju",byQuantity:"Po prodatoj količini",sales:"Prodaja",ordersByHour:"Porudžbine po satu",performance:"Učinak",popularItems:"Popularni proizvodi",activity:"Aktivnost",recentOrders:"Poslednje porudžbine",noSales:"Još nema prodaje",qty:"prodato",resetConfirm:"Resetovati sve demo podatke?",demoReset:"Demo podaci su resetovani",exported:"Izveštaj je izvezen"}
};
let language=localStorage.getItem("kafa-language")||"sr";
let products=JSON.parse(localStorage.getItem("kafa-products")||"null")||structuredClone(defaultProducts);
let orders=JSON.parse(localStorage.getItem("kafa-orders")||"[]");
let cart=[];let activeCategory="all";let service="dineIn";let orderSequence=Number(localStorage.getItem("kafa-sequence")||1048);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem("kafa-products",JSON.stringify(products));localStorage.setItem("kafa-orders",JSON.stringify(orders));localStorage.setItem("kafa-sequence",orderSequence);localStorage.setItem("kafa-language",language)}
function money(n){return `${Number(n).toLocaleString(language==="sr"?"sr-RS":"en-US")} RSD`}
function t(k){return tr[language][k]||k}
function setLanguage(lang){language=lang;document.documentElement.lang=lang;$$('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));$$('[data-placeholder]').forEach(el=>el.placeholder=t(el.dataset.placeholder));save();renderAll()}
function renderCategories(){const categories=["all","coffee","cold","food","dessert"];$("#categoryFilters").innerHTML=categories.map(c=>`<button class="category-button ${activeCategory===c?'active':''}" data-category="${c}">${t(c)}</button>`).join("");$$('.category-button').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;renderCategories();renderProducts()})}
function renderProducts(){const q=$("#productSearch").value.toLowerCase();const list=products.filter(p=>(activeCategory==="all"||p.category===activeCategory)&&(p.name.toLowerCase().includes(q)||p.description.toLowerCase().includes(q)));$("#productGrid").innerHTML=list.map(p=>`<button class="product-card" data-product="${p.id}" ${p.available?'':'disabled'}><span class="product-visual ${p.category}">${p.icon}${p.available?'':`<i class="sold-out">${t('soldOut')}</i>`}</span><span class="product-info"><span><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.description)}</small></span><span>${money(p.price)}</span></span></button>`).join("");$$('[data-product]').forEach(b=>b.onclick=()=>addToCart(Number(b.dataset.product)))}
function addToCart(id){const existing=cart.find(i=>i.id===id);if(existing)existing.qty++;else{const p=products.find(p=>p.id===id);cart.push({...p,qty:1});toast(`${p.name} added`)}renderCart()}
function updateCart(id,delta){const item=cart.find(i=>i.id===id);if(!item)return;item.qty+=delta;if(item.qty<=0)cart=cart.filter(i=>i.id!==id);renderCart()}
function renderCart(){const total=cart.reduce((s,i)=>s+i.price*i.qty,0);$("#cart").innerHTML=cart.length?cart.map(i=>`<div class="cart-row"><div><strong>${escapeHtml(i.name)}</strong><small>${money(i.price)} × ${i.qty}</small><div class="cart-controls"><button data-minus="${i.id}">−</button><span>${i.qty}</span><button data-plus="${i.id}">+</button></div></div><span class="cart-price">${money(i.price*i.qty)}</span></div>`).join(""):`<div class="empty-cart"><span>☕</span><strong>${t('emptyOrder')}</strong><p>${t('addFromMenu')}</p></div>`;$("#subtotal").textContent=$("#total").textContent=$("#sendTotal").textContent=money(total);$("#sendOrder").disabled=!cart.length;$$('[data-minus]').forEach(b=>b.onclick=()=>updateCart(Number(b.dataset.minus),-1));$$('[data-plus]').forEach(b=>b.onclick=()=>updateCart(Number(b.dataset.plus),1))}
function sendOrder(){if(!cart.length)return toast(t('orderEmpty'));const now=new Date();orders.unshift({id:orderSequence++,items:cart.map(i=>({id:i.id,name:i.name,price:i.price,qty:i.qty})),total:cart.reduce((s,i)=>s+i.price*i.qty,0),service,table:service==="dineIn"?$("#tableSelect").value:null,status:"waiting",createdAt:now.toISOString()});cart=[];save();$("#orderNumber").textContent=`#${orderSequence}`;renderAll();toast(t('orderSent'));openView('kitchen')}
function renderKitchen(){const statuses=["waiting","preparing","ready"];const active=orders.filter(o=>statuses.includes(o.status));$("#kitchenCount").textContent=active.filter(o=>o.status!=="ready").length;statuses.forEach(s=>$(`#${s}Count`).textContent=active.filter(o=>o.status===s).length);$("#kitchenBoard").innerHTML=statuses.map(status=>{const list=active.filter(o=>o.status===status);return `<div class="kanban-column"><div class="kanban-title"><span>${t(status)}</span><span>${list.length}</span></div>${list.length?list.map(o=>ticket(o)).join(''):`<div class="empty-column">${t('noOrders')}</div>`}</div>`}).join("");$$('[data-advance]').forEach(b=>b.onclick=()=>advanceOrder(Number(b.dataset.advance)))}
function ticket(o){const next=o.status==="waiting"?t('startPreparing'):t('markReady');const mins=Math.max(0,Math.round((Date.now()-new Date(o.createdAt))/60000));return `<article class="ticket ${o.status}"><div class="ticket-head"><strong>#${o.id}</strong><span>${mins} min</span></div><div class="ticket-meta">${o.service==="dineIn"?`${t('table')} ${String(o.table).padStart(2,'0')}`:t('takeaway')} · ${new Date(o.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div><ul>${o.items.map(i=>`<li><span>${i.qty}× ${escapeHtml(i.name)}</span></li>`).join('')}</ul><button data-advance="${o.id}">${next}</button></article>`}
function advanceOrder(id){const o=orders.find(o=>o.id===id);if(!o)return;o.status=o.status==="waiting"?"preparing":"ready";save();renderAll()}
function renderMenu(){const available=products.filter(p=>p.available).length;$("#totalItems").textContent=products.length;$("#availableItems").textContent=available;$("#unavailableItems").textContent=products.length-available;$("#menuTable").innerHTML=products.map(p=>`<tr><td><div class="item-cell"><span class="mini-icon">${p.icon}</span><span><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.description)}</small></span></div></td><td>${t(p.category)}</td><td><strong>${money(p.price)}</strong></td><td><span class="availability ${p.available?'':'off'}"><i></i>${p.available?t('available'):t('unavailable')}</span></td><td><button class="toggle ${p.available?'on':''}" data-toggle="${p.id}" aria-label="Toggle availability"><i></i></button> <button class="delete-item" data-delete="${p.id}" aria-label="Delete">×</button></td></tr>`).join("");$$('[data-toggle]').forEach(b=>b.onclick=()=>{const p=products.find(p=>p.id===Number(b.dataset.toggle));p.available=!p.available;save();renderAll()});$$('[data-delete]').forEach(b=>b.onclick=()=>{products=products.filter(p=>p.id!==Number(b.dataset.delete));save();renderAll()})}
function renderReports(){const revenue=orders.reduce((s,o)=>s+o.total,0);$("#revenueMetric").textContent=money(revenue).replace(' RSD','');$("#ordersMetric").textContent=orders.length;$("#averageMetric").textContent=orders.length?Math.round(revenue/orders.length).toLocaleString():0;const counts={};orders.forEach(o=>o.items.forEach(i=>counts[i.name]=(counts[i.name]||0)+i.qty));const popular=Object.entries(counts).sort((a,b)=>b[1]-a[1]);$("#topItemMetric").textContent=popular[0]?.[0]||"—";$("#popularItems").innerHTML=popular.length?popular.slice(0,6).map(([name,count])=>`<div class="popular-row"><span><strong>${escapeHtml(name)}</strong><small>${count} ${t('qty')}</small></span><strong>${count}</strong></div>`).join(''):`<div class="empty-column">${t('noSales')}</div>`;const hours=Array.from({length:12},(_,i)=>i+8);const hourCounts=hours.map(h=>orders.filter(o=>new Date(o.createdAt).getHours()===h).length);const max=Math.max(1,...hourCounts);$("#salesChart").innerHTML=hours.map((h,i)=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(2,hourCounts[i]/max*100)}%" data-value="${hourCounts[i]}"></div><small>${h}:00</small></div>`).join('');$("#recentOrders").innerHTML=orders.length?orders.slice(0,8).map(o=>`<div class="recent-row"><strong>#${o.id}</strong><span>${o.items.map(i=>`${i.qty}× ${escapeHtml(i.name)}`).join(', ')}</span><span>${new Date(o.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><strong>${money(o.total)}</strong></div>`).join(''):`<div class="empty-column">${t('noSales')}</div>`}
function renderAll(){renderCategories();renderProducts();renderCart();renderKitchen();renderMenu();renderReports()}
function openView(view){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${view}-view`));if(innerWidth<761)scrollTo({top:0,behavior:'smooth'})}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2200)}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function exportCsv(){const rows=[["Order","Time","Service","Table","Items","Total RSD","Status"],...orders.map(o=>[o.id,o.createdAt,o.service,o.table||"",o.items.map(i=>`${i.qty}x ${i.name}`).join("; "),o.total,o.status])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kafa-daily-report.csv';a.click();URL.revokeObjectURL(a.href);toast(t('exported'))}
$$('.nav-item').forEach(b=>b.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${b.dataset.view}-view`));if(innerWidth<761)scrollTo({top:0,behavior:'smooth'})});$("#productSearch").oninput=renderProducts;$("#clearOrder").onclick=()=>{cart=[];renderCart()};$("#sendOrder").onclick=sendOrder;$$('[data-service]').forEach(b=>b.onclick=()=>{service=b.dataset.service;$$('[data-service]').forEach(x=>x.classList.toggle('active',x===b));$(".table-select").style.display=service==="dineIn"?'flex':'none'});$("#languageButton").onclick=()=>setLanguage(language==="sr"?"en":"sr");$("#clearCompleted").onclick=()=>{orders=orders.filter(o=>o.status!=="ready");save();renderAll()};$("#addItemButton").onclick=()=>$("#itemDialog").showModal();$("#itemForm").onsubmit=e=>{if(e.submitter?.value==='cancel')return;const price=Number($("#newItemPrice").value);if(!$("#newItemName").value.trim()||price<1){e.preventDefault();return}products.push({id:Date.now(),name:$("#newItemName").value.trim(),description:$("#newItemDescription").value.trim()||"Custom menu item",category:$("#newItemCategory").value,price,icon:{coffee:"☕",cold:"🥤",food:"🥪",dessert:"🍰"}[$("#newItemCategory").value],available:true});save();setTimeout(()=>{$("#itemForm").reset();renderAll();toast(t('itemAdded'))},0)};$("#resetButton").onclick=()=>{if(!confirm(t('resetConfirm')))return;products=structuredClone(defaultProducts);orders=[];cart=[];orderSequence=1048;save();renderAll();toast(t('demoReset'))};$("#exportButton").onclick=exportCsv;
function updateClock(){const now=new Date();$("#dateLabel").textContent=now.toLocaleDateString(language==="sr"?"sr-Latn-RS":"en-GB",{weekday:"long",day:"numeric",month:"short"});$("#clockLabel").textContent=now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}setInterval(updateClock,1000);setLanguage(language);updateClock();
