const cars=[
 {id:1,brand:"Porsche",model:"911 Carrera GTS",year:2024,price:168900,hp:532,zero:3.0,transmission:"Automatic",drive:"AWD",tone:"#5b1515"},
 {id:2,brand:"BMW",model:"M3 Competition",year:2023,price:98500,hp:503,zero:3.5,transmission:"Automatic",drive:"AWD",tone:"#174b62"},
 {id:3,brand:"Lotus",model:"Emira V6",year:2024,price:109900,hp:400,zero:4.3,transmission:"Manual",drive:"RWD",tone:"#173f2b"},
 {id:4,brand:"Audi",model:"RS 6 Avant",year:2023,price:146000,hp:621,zero:3.4,transmission:"Automatic",drive:"AWD",tone:"#42474e"},
 {id:5,brand:"Nissan",model:"GT-R Premium",year:2022,price:132000,hp:565,zero:2.9,transmission:"Automatic",drive:"AWD",tone:"#45376a"},
 {id:6,brand:"Ford",model:"Mustang Dark Horse",year:2024,price:74900,hp:500,zero:4.1,transmission:"Manual",drive:"RWD",tone:"#1b3563"},
 {id:7,brand:"Mercedes",model:"AMG GT 63",year:2024,price:187500,hp:577,zero:3.1,transmission:"Automatic",drive:"AWD",tone:"#504d46"},
 {id:8,brand:"Toyota",model:"GR Supra",year:2023,price:68900,hp:382,zero:3.9,transmission:"Manual",drive:"RWD",tone:"#81251f"}
];
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n);
let saved=JSON.parse(localStorage.getItem("apex-saved")||"[]"),compare=[],savedOnly=false;
const searchInput=$("#searchInput"),brandFilter=$("#brandFilter"),transmissionFilter=$("#transmissionFilter"),priceFilter=$("#priceFilter");
function renderBrands(){brandFilter.innerHTML+=[...new Set(cars.map(c=>c.brand))].map(b=>`<option>${b}</option>`).join("")}
function filteredCars(){const q=searchInput.value.toLowerCase();return cars.filter(c=>(!savedOnly||saved.includes(c.id))&&(!q||`${c.brand} ${c.model}`.toLowerCase().includes(q))&&(brandFilter.value==="all"||c.brand===brandFilter.value)&&(transmissionFilter.value==="all"||c.transmission===transmissionFilter.value)&&c.price<=Number(priceFilter.value))}
function renderCars(){const list=filteredCars();$("#resultCount").textContent=`${list.length} vehicle${list.length===1?"":"s"}`;$("#emptyState").hidden=!!list.length;$("#carGrid").innerHTML=list.map(c=>`<article class="car-card"><div class="car-visual" style="--tone:${c.tone}"><button class="save ${saved.includes(c.id)?"active":""}" data-save="${c.id}" aria-label="Save ${c.brand} ${c.model}">♥</button></div><div class="car-info"><div class="car-title"><h3>${c.brand} ${c.model}</h3><strong>${money(c.price)}</strong></div><p>${c.year} · Demo listing</p><div class="specs"><span>POWER<b>${c.hp} hp</b></span><span>0–100<b>${c.zero}s</b></span><span>GEARBOX<b>${c.transmission}</b></span></div><div class="card-actions"><button class="details" data-details="${c.id}">View details</button><button data-compare="${c.id}">${compare.includes(c.id)?"Added":"Compare"}</button></div></div></article>`).join("");document.querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>toggleSaved(Number(b.dataset.save)));document.querySelectorAll("[data-details]").forEach(b=>b.onclick=()=>openDetails(Number(b.dataset.details)));document.querySelectorAll("[data-compare]").forEach(b=>b.onclick=()=>toggleCompare(Number(b.dataset.compare)))}
function toggleSaved(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem("apex-saved",JSON.stringify(saved));updateSaved();renderCars();toast(saved.includes(id)?"Vehicle saved":"Vehicle removed")}
function updateSaved(){$("#savedCount").textContent=saved.length}
function toggleCompare(id){if(compare.includes(id))compare=compare.filter(x=>x!==id);else if(compare.length<2)compare.push(id);else return toast("Remove a comparison first");renderCompare();renderCars()}
function renderCompare(){const selected=compare.map(id=>cars.find(c=>c.id===id));$("#compareGrid").innerHTML=[0,1].map(i=>{const c=selected[i];return c?`<article class="compare-slot filled"><p class="eyebrow">Vehicle ${i+1}</p><h3>${c.brand} ${c.model}</h3><div class="compare-row"><span>Price</span><strong>${money(c.price)}</strong></div><div class="compare-row"><span>Power</span><strong>${c.hp} hp</strong></div><div class="compare-row"><span>0–100 km/h</span><strong>${c.zero}s</strong></div><div class="compare-row"><span>Drivetrain</span><strong>${c.drive}</strong></div><button class="remove-compare" data-remove="${c.id}">Remove</button></article>`:`<div class="compare-slot"><span>Select vehicle ${i+1}<br>from the inventory</span></div>`}).join("");document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>toggleCompare(Number(b.dataset.remove)))}
function openDetails(id){const c=cars.find(c=>c.id===id);$("#dialogContent").innerHTML=`<div class="dialog-layout"><div class="dialog-visual" style="--tone:${c.tone}"></div><div class="dialog-copy"><p class="eyebrow">${c.year} performance collection</p><h2>${c.brand}<br>${c.model}</h2><strong>${money(c.price)}</strong><dl><div><dt>Power</dt><dd>${c.hp} hp</dd></div><div><dt>0–100 km/h</dt><dd>${c.zero}s</dd></div><div><dt>Transmission</dt><dd>${c.transmission}</dd></div><div><dt>Drive</dt><dd>${c.drive}</dd></div></dl><p>Fictional specifications and pricing for portfolio demonstration only.</p><button class="button primary" data-enquire="${c.id}">Enquire</button></div></div>`;$("#carDialog").showModal();$("[data-enquire]").onclick=()=>openEnquiry(c)}
function openEnquiry(c){$("#carDialog").close();$("#enquiryTitle").textContent=`${c.brand} ${c.model}`;$("#enquiryForm").dataset.car=c.id;$("#enquiryDialog").showModal()}
function calculate(){const price=Number($("#calcPrice").value),deposit=Math.min(Number($("#calcDeposit").value),price),months=Number($("#calcTerm").value),rate=.069/12;const payment=(price-deposit)*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1);$("#priceValue").textContent=money(price);$("#depositValue").textContent=money(deposit);$("#monthlyEstimate").textContent=money(Math.round(payment))}
function clearFilters(){savedOnly=false;searchInput.value="";brandFilter.value="all";transmissionFilter.value="all";priceFilter.value="999999";renderCars()}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2200)}
[searchInput,brandFilter,transmissionFilter,priceFilter].forEach(el=>el.addEventListener(el===searchInput?"input":"change",()=>{savedOnly=false;renderCars()}));$("#clearFilters").onclick=$("#emptyReset").onclick=clearFilters;$("#dialogClose").onclick=()=>$("#carDialog").close();$("#enquiryClose").onclick=()=>$("#enquiryDialog").close();$("#enquiryForm").onsubmit=e=>{e.preventDefault();$("#enquiryDialog").close();e.target.reset();toast("Demo enquiry completed")};$("#featuredButton").onclick=()=>openDetails(1);$("#savedButton").onclick=()=>{if(!saved.length)return toast("No saved vehicles yet");savedOnly=!savedOnly;searchInput.value="";brandFilter.value="all";transmissionFilter.value="all";priceFilter.value="999999";renderCars();$("#inventory").scrollIntoView({behavior:"smooth"});toast(savedOnly?"Showing saved vehicles":"Showing all vehicles")};[$("#calcPrice"),$("#calcDeposit"),$("#calcTerm")].forEach(el=>el.oninput=calculate);renderBrands();renderCars();renderCompare();updateSaved();calculate();
